apiVersion: appprotect.f5.com/v1beta1
kind: APPolicy
metadata: 
  name: high-accuracy-attack-sigs
  namespace: nginx-plus-ingress-ns
spec:
  policy:
    name: attack_sigs
    template:
      name: POLICY_TEMPLATE_NGINX_BASE
    applicationLanguage: utf-8
    enforcementMode: blocking
    signature-sets:
    - name: High Accuracy Signatures
      block: true
      alarm: true
