apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: rate-limit-policy
  namespace: nginx-plus-ingress-ns
spec:
  rateLimit:
    rate: 10r/m
    key: ${binary_remote_addr}
    zoneSize: 10M
    rejectCode: 429