apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: waf-http-compliance-waf
  namespace: nginx-plus-ingress-ns
spec:
  waf:
    enable: true
    apPolicy: "nginx-plus-ingress-ns/http-compliance"
