global:
templates:
- "/etc/alertmanager/*.tmpl"
route:
  receiver: alert-emailer
  group_by:
  - alertname
  - priority
  group_wait: 10s
  repeat_interval: 30m
  #routes:
  #- receiver: slack_demo
    #match:
      #severity: slack
    #group_wait: 10s
    #repeat_interval: 1m
receivers:
- name: alert-emailer
  email_configs:
  - to: admin@your-kube-server.com
    send_resolved: false
    from: admin@your-kube-server.com
    smarthost: smtp.kubecluster.com:25
    require_tls: false
#- name: slack_demo
  #slack_configs:
  #- api_url: https://your.slack.service
    #channel: "#devops-team"
